/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signup */
        post: operations["signup_api_v1_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Password Reset
         * @description 가입 여부와 관계없이 같은 응답을 준다 (이메일 존재 여부 노출 방지).
         */
        post: operations["request_password_reset_api_v1_auth_password_reset_request_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Password Reset */
        post: operations["confirm_password_reset_api_v1_auth_password_reset_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Threads */
        get: operations["list_threads_api_v1_threads_get"];
        put?: never;
        /** Create Thread */
        post: operations["create_thread_api_v1_threads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/threads/{thread_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Thread */
        get: operations["get_thread_api_v1_threads__thread_id__get"];
        put?: never;
        post?: never;
        /** Delete Thread */
        delete: operations["delete_thread_api_v1_threads__thread_id__delete"];
        options?: never;
        head?: never;
        /** Update Thread */
        patch: operations["update_thread_api_v1_threads__thread_id__patch"];
        trace?: never;
    };
    "/api/v1/threads/{thread_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Messages */
        get: operations["list_messages_api_v1_threads__thread_id__messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/threads/{thread_id}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description 메시지를 보내고 에이전트 응답을 SSE 로 스트리밍한다 (Vercel AI SDK useChat 호환).
         *
         *     서버 키 모델인데 크레딧이 없으면 402. 사용자가 등록한 키의 모델은 크레딧과 무관하게 쓸 수 있다.
         */
        post: operations["chat_api_v1_threads__thread_id__chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Agents */
        get: operations["list_agents_api_v1_agents_get"];
        put?: never;
        /** Create Agent */
        post: operations["create_agent_api_v1_agents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Agent */
        get: operations["get_agent_api_v1_agents__agent_id__get"];
        put?: never;
        post?: never;
        /** Delete Agent */
        delete: operations["delete_agent_api_v1_agents__agent_id__delete"];
        options?: never;
        head?: never;
        /** Update Agent */
        patch: operations["update_agent_api_v1_agents__agent_id__patch"];
        trace?: never;
    };
    "/api/v1/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workflows */
        get: operations["list_workflows_api_v1_workflows_get"];
        put?: never;
        /** Create Workflow */
        post: operations["create_workflow_api_v1_workflows_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflow_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workflow */
        get: operations["get_workflow_api_v1_workflows__workflow_id__get"];
        put?: never;
        post?: never;
        /** Delete Workflow */
        delete: operations["delete_workflow_api_v1_workflows__workflow_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Workflow
         * @description 그래프는 미완성이어도 저장할 수 있다. 검증은 실행할 때 한다.
         */
        patch: operations["update_workflow_api_v1_workflows__workflow_id__patch"];
        trace?: never;
    };
    "/api/v1/workflows/{workflow_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Workflow */
        post: operations["run_workflow_api_v1_workflows__workflow_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflow_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish Workflow
         * @description 지금 저장된 편집본을 배포본으로. 외부 API·공개 링크는 배포본만 실행한다.
         */
        post: operations["publish_workflow_api_v1_workflows__workflow_id__publish_post"];
        /**
         * Unpublish Workflow
         * @description 배포를 내린다. 외부 API·공개 링크 호출은 바로 거부된다.
         */
        delete: operations["unpublish_workflow_api_v1_workflows__workflow_id__publish_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflow_id}/embed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Embed
         * @description 공개 링크 (iframe). 만든 적 없으면 null.
         */
        get: operations["get_embed_api_v1_workflows__workflow_id__embed_get"];
        /**
         * Upsert Embed
         * @description 공개 링크를 만들거나 설정을 바꾼다. 주소(token)는 처음 만들 때 한 번 정해진다.
         */
        put: operations["upsert_embed_api_v1_workflows__workflow_id__embed_put"];
        post?: never;
        /**
         * Delete Embed
         * @description 공개 링크를 없앤다. 다시 만들면 주소가 바뀐다.
         */
        delete: operations["delete_embed_api_v1_workflows__workflow_id__embed_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflow_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Workflow Runs
         * @description 최근 실행 기록 (새것부터).
         */
        get: operations["list_workflow_runs_api_v1_workflows__workflow_id__runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Providers */
        get: operations["list_providers_api_v1_providers_get"];
        put?: never;
        /**
         * Create Provider
         * @description 실제 API 로 키를 확인한 뒤에만 저장한다.
         */
        post: operations["create_provider_api_v1_providers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/{provider_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Provider */
        delete: operations["delete_provider_api_v1_providers__provider_id__delete"];
        options?: never;
        head?: never;
        /** Update Provider */
        patch: operations["update_provider_api_v1_providers__provider_id__patch"];
        trace?: never;
    };
    "/api/v1/providers/{provider_id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Provider
         * @description 저장된 키로 다시 확인하고 모델 목록을 새로 받는다.
         */
        post: operations["verify_provider_api_v1_providers__provider_id__verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/{provider_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Provider Model
         * @description 모델에 짧은 요청을 실제로 보내본다. 크레딧 부족·모델 권한 문제도 여기서 드러난다.
         */
        post: operations["test_provider_model_api_v1_providers__provider_id__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run
         * @description 실행 한 번의 입력·노드별 결과·최종 출력.
         */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Feedback
         * @description 채팅 답변·워크플로우 실행에 👍/👎. Langfuse 기록에는 user-feedback 점수로 붙는다.
         */
        put: operations["set_feedback_api_v1_runs__run_id__feedback_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Usage
         * @description 최근 N일 모델 사용량과 비용. 모델 호출마다 남긴 기록을 모은다.
         */
        get: operations["get_usage_api_v1_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/credits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My Credits
         * @description 내 크레딧 잔액과 최근 충전·사용 내역.
         */
        get: operations["my_credits_api_v1_credits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/credits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * User Credits
         * @description (관리자) 사용자의 크레딧 잔액과 내역.
         */
        get: operations["user_credits_api_v1_admin_credits_get"];
        put?: never;
        /**
         * Grant Credits
         * @description (관리자) 크레딧 충전. 음수면 조정(회수). 결제 연동 전 초기 고객 운영용.
         */
        post: operations["grant_credits_api_v1_admin_credits_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Api Keys */
        get: operations["list_api_keys_api_v1_api_keys_get"];
        put?: never;
        /**
         * Create Api Key
         * @description 키 원문은 이 응답에서만 한 번 보여 준다.
         */
        post: operations["create_api_key_api_v1_api_keys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/api-keys/{key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Api Key
         * @description 지우면 그 키로 오는 요청은 바로 거부된다.
         */
        delete: operations["delete_api_key_api_v1_api_keys__key_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ext/workflows/{workflow_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Workflow
         * @description 배포된 워크플로우를 실행한다. 기본은 끝날 때까지 기다렸다가 결과를 한 번에 돌려준다.
         */
        post: operations["run_workflow_api_v1_ext_workflows__workflow_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/embeds/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Embed */
        get: operations["get_embed_api_v1_public_embeds__token__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/embeds/{token}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Embed */
        post: operations["run_embed_api_v1_public_embeds__token__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integrations/telegram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Telegram */
        get: operations["get_telegram_api_v1_integrations_telegram_get"];
        /**
         * Connect Telegram
         * @description 토큰을 확인하고, 봇에게 말을 건 내 채팅을 찾아 연결한다. 연결되면 확인 메시지를 보낸다.
         */
        put: operations["connect_telegram_api_v1_integrations_telegram_put"];
        post?: never;
        /** Disconnect Telegram */
        delete: operations["disconnect_telegram_api_v1_integrations_telegram_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integrations/telegram/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Telegram */
        post: operations["test_telegram_api_v1_integrations_telegram_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tools */
        get: operations["list_tools_api_v1_tools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Models
         * @description 이 사용자가 쓸 수 있는 모델 (설정에서 켠 모델 + .env 대체 모델).
         */
        get: operations["list_models_api_v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Default Model */
        put: operations["set_default_model_api_v1_models_default_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentCreate */
        AgentCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** System Prompt */
            system_prompt: string;
            /** Model */
            model?: string | null;
            /**
             * Tools
             * @default []
             */
            tools: string[];
        };
        /** AgentRead */
        AgentRead: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** System Prompt */
            system_prompt: string;
            /** Model */
            model: string | null;
            /** Tools */
            tools: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** AgentUpdate */
        AgentUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** System Prompt */
            system_prompt?: string | null;
            /** Model */
            model?: string | null;
            /** Tools */
            tools?: string[] | null;
        };
        /** ApiKeyCreate */
        ApiKeyCreate: {
            /** Name */
            name: string;
            /** Workflow Ids */
            workflow_ids?: string[] | null;
        };
        /** ApiKeyCreated */
        ApiKeyCreated: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Prefix */
            prefix: string;
            /** Workflow Ids */
            workflow_ids: string[] | null;
            /** Last Used At */
            last_used_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Key */
            key: string;
        };
        /** ApiKeyRead */
        ApiKeyRead: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Prefix */
            prefix: string;
            /** Workflow Ids */
            workflow_ids: string[] | null;
            /** Last Used At */
            last_used_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Message */
            message: string;
            /** Model */
            model?: string | null;
        };
        /** Credentials */
        Credentials: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** CreditGrant */
        CreditGrant: {
            /** Email */
            email: string;
            /** Amount */
            amount: number;
            /** Note */
            note?: string | null;
        };
        /** CreditTransactionRead */
        CreditTransactionRead: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "grant" | "usage" | "adjust";
            /** Amount */
            amount: number;
            /** Run Id */
            run_id: string | null;
            /** Note */
            note: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CreditsRead */
        CreditsRead: {
            /** Balance */
            balance: number;
            /** Enforced */
            enforced: boolean;
            /** Credits Per Usd */
            credits_per_usd: number;
            /** Transactions */
            transactions: components["schemas"]["CreditTransactionRead"][];
        };
        /** DefaultModelUpdate */
        DefaultModelUpdate: {
            /** Model */
            model: string;
        };
        /**
         * EmbedPublic
         * @description 공개 페이지가 그릴 정보. 로그인 없이 보이므로 이름·설명 말고는 내보내지 않는다.
         */
        EmbedPublic: {
            /**
             * Kind
             * @default workflow
             * @constant
             */
            kind: "workflow";
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Allowed Origins */
            allowed_origins: string[];
        };
        /** EmbedRead */
        EmbedRead: {
            /** Token */
            token: string;
            /** Enabled */
            enabled: boolean;
            /** Allowed Origins */
            allowed_origins: string[];
            /** Daily Limit */
            daily_limit: number;
            /**
             * Today Runs
             * @default 0
             */
            today_runs: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** EmbedRunRequest */
        EmbedRunRequest: {
            /**
             * Input
             * @default
             */
            input: string;
        };
        /** EmbedRunResult */
        EmbedRunResult: {
            /**
             * Status
             * @enum {string}
             */
            status: "done" | "error";
            /** Output */
            output?: string | null;
            /** Error */
            error?: string | null;
        };
        /** EmbedUpdate */
        EmbedUpdate: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Allowed Origins
             * @default []
             */
            allowed_origins: string[];
            /**
             * Daily Limit
             * @default 100
             */
            daily_limit: number;
        };
        /** ExtRunRequest */
        ExtRunRequest: {
            /**
             * Input
             * @default
             */
            input: string;
            /**
             * Stream
             * @default false
             */
            stream: boolean;
        };
        /** ExtRunResult */
        ExtRunResult: {
            /** Run Id */
            run_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "done" | "error";
            /** Output */
            output?: string | null;
            /** Error */
            error?: string | null;
        };
        /** FeedbackRead */
        FeedbackRead: {
            /** Run Id */
            run_id: string;
            /** Feedback */
            feedback: number | null;
        };
        /** FeedbackUpdate */
        FeedbackUpdate: {
            /**
             * Value
             * @enum {integer}
             */
            value: 1 | -1;
            /** Comment */
            comment?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** ModelOption */
        ModelOption: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Provider */
            provider: string;
            /**
             * Billing
             * @enum {string}
             */
            billing: "platform" | "user" | "free";
            /** Blocked Reason */
            blocked_reason?: string | null;
        };
        /** ModelTestRequest */
        ModelTestRequest: {
            /** Model */
            model: string;
        };
        /** ModelTestResult */
        ModelTestResult: {
            /** Ok */
            ok: boolean;
            /** Reply */
            reply?: string | null;
            /** Error */
            error?: string | null;
            /** Latency Ms */
            latency_ms?: number | null;
        };
        /** ModelsRead */
        ModelsRead: {
            /** Default */
            default: string | null;
            /** Options */
            options: components["schemas"]["ModelOption"][];
        };
        /** NodePosition */
        NodePosition: {
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** PasswordResetConfirm */
        PasswordResetConfirm: {
            /** Token */
            token: string;
            /** New Password */
            new_password: string;
        };
        /** PasswordResetRequest */
        PasswordResetRequest: {
            /** Email */
            email: string;
        };
        /** ProviderCreate */
        ProviderCreate: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "anthropic" | "openai" | "openai_compatible";
            /** Name */
            name?: string | null;
            /** Api Key */
            api_key?: string | null;
            /** Base Url */
            base_url?: string | null;
        };
        /** ProviderModelRead */
        ProviderModelRead: {
            /** Id */
            id: string;
            /** Label */
            label: string;
        };
        /** ProviderRead */
        ProviderRead: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /** Base Url */
            base_url: string | null;
            /** Api Key Hint */
            api_key_hint: string | null;
            /** Available Models */
            available_models: components["schemas"]["ProviderModelRead"][];
            /** Enabled Models */
            enabled_models: string[];
            /** Verified At */
            verified_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ProviderUpdate */
        ProviderUpdate: {
            /** Name */
            name?: string | null;
            /** Api Key */
            api_key?: string | null;
            /** Base Url */
            base_url?: string | null;
            /** Enabled Models */
            enabled_models?: string[] | null;
        };
        /** RunDetail */
        RunDetail: {
            /** Id */
            id: string;
            /** Trigger */
            trigger?: string | null;
            /** Status */
            status: string | null;
            /** Input */
            input: string | null;
            /** Output */
            output: string | null;
            /** Error */
            error: string | null;
            /** Feedback */
            feedback: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Steps */
            steps: components["schemas"]["RunStep"][];
        };
        /** RunStep */
        RunStep: {
            /** Node Id */
            node_id: string;
            /** Status */
            status: string;
            /** Output */
            output?: string | null;
            /** Error */
            error?: string | null;
        };
        /** RunSummary */
        RunSummary: {
            /** Id */
            id: string;
            /** Trigger */
            trigger?: string | null;
            /** Status */
            status: string | null;
            /** Input */
            input: string | null;
            /** Output */
            output: string | null;
            /** Error */
            error: string | null;
            /** Feedback */
            feedback: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finished At */
            finished_at: string | null;
        };
        /** TelegramConnect */
        TelegramConnect: {
            /** Bot Token */
            bot_token: string;
        };
        /** TelegramStatus */
        TelegramStatus: {
            /** Connected */
            connected: boolean;
            /** Bot Username */
            bot_username?: string | null;
            /** Chat Name */
            chat_name?: string | null;
            /** Token Hint */
            token_hint?: string | null;
        };
        /** ThreadCreate */
        ThreadCreate: {
            /** Title */
            title?: string | null;
            /** Model */
            model?: string | null;
            /** Agent Id */
            agent_id?: string | null;
        };
        /** ThreadRead */
        ThreadRead: {
            /** Id */
            id: string;
            /** Title */
            title: string | null;
            /** Model */
            model: string | null;
            /** Agent Id */
            agent_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ThreadUpdate */
        ThreadUpdate: {
            /** Title */
            title?: string | null;
            /** Model */
            model?: string | null;
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
        };
        /** ToolRead */
        ToolRead: {
            /** Name */
            name: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /** Example Args */
            example_args: string;
        };
        /**
         * UIMessage
         * @description Vercel AI SDK 의 UIMessage 와 같은 모양.
         */
        UIMessage: {
            /** Id */
            id: string;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Parts */
            parts: {
                [key: string]: unknown;
            }[];
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /** UsageDay */
        UsageDay: {
            /** Date */
            date: string;
            /** Cost */
            cost: number;
            /** Tokens */
            tokens: number;
        };
        /** UsageRead */
        UsageRead: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Days */
            days: number;
            /**
             * Total Cost
             * @default 0
             */
            total_cost: number;
            /**
             * Total Tokens
             * @default 0
             */
            total_tokens: number;
            /**
             * Calls
             * @default 0
             */
            calls: number;
            /**
             * Unpriced Calls
             * @default 0
             */
            unpriced_calls: number;
            /**
             * By Model
             * @default []
             */
            by_model: components["schemas"]["UsageRow"][];
            /**
             * By Source
             * @default []
             */
            by_source: components["schemas"]["UsageRow"][];
            /**
             * By Billing
             * @default []
             */
            by_billing: components["schemas"]["UsageRow"][];
            /**
             * Daily
             * @default []
             */
            daily: components["schemas"]["UsageDay"][];
            /** Error */
            error?: string | null;
        };
        /** UsageRow */
        UsageRow: {
            /** Name */
            name: string;
            /** Cost */
            cost: number;
            /** Tokens */
            tokens: number;
            /** Calls */
            calls: number;
            /**
             * Unpriced Calls
             * @default 0
             */
            unpriced_calls: number;
        };
        /** UserRead */
        UserRead: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkflowCreate */
        WorkflowCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            graph?: components["schemas"]["WorkflowGraph"] | null;
        };
        /** WorkflowEdge */
        WorkflowEdge: {
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Sourcehandle */
            sourceHandle?: string | null;
        };
        /** WorkflowGraph */
        WorkflowGraph: {
            /**
             * Nodes
             * @default []
             */
            nodes: components["schemas"]["WorkflowNode"][];
            /**
             * Edges
             * @default []
             */
            edges: components["schemas"]["WorkflowEdge"][];
        };
        /**
         * WorkflowNode
         * @description React Flow 노드와 같은 모양. 화면 전용 필드(selected, measured 등)는 저장하지 않는다.
         */
        WorkflowNode: {
            /** Id */
            id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "start" | "llm" | "agent" | "tool" | "condition" | "end";
            position: components["schemas"]["NodePosition"];
            /**
             * Data
             * @default {}
             */
            data: {
                [key: string]: unknown;
            };
        };
        /** WorkflowRead */
        WorkflowRead: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            graph: components["schemas"]["WorkflowGraph"];
            published_graph?: components["schemas"]["WorkflowGraph"] | null;
            /** Published At */
            published_at?: string | null;
            schedule?: components["schemas"]["WorkflowSchedule"] | null;
            /**
             * Delete Protected
             * @default false
             */
            delete_protected: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Has Unpublished Changes
             * @description 배포한 뒤 편집본을 실행에 영향이 가게 고쳤는지 (배포 전이면 False). 노드 위치만 옮긴 것은 치지 않는다.
             */
            readonly has_unpublished_changes: boolean;
            /**
             * Next Run At
             * @description 다음 예약 실행 시각
             */
            readonly next_run_at: string | null;
        };
        /** WorkflowRunRequest */
        WorkflowRunRequest: {
            /**
             * Input
             * @default
             */
            input: string;
        };
        /**
         * WorkflowSchedule
         * @description 예약 실행. 한국 시간 기준.
         */
        WorkflowSchedule: {
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Time
             * @example 08:00
             */
            time: string;
            /**
             * Weekdays
             * @default [
             *       0,
             *       1,
             *       2,
             *       3,
             *       4,
             *       5,
             *       6
             *     ]
             */
            weekdays: number[];
            /**
             * Input
             * @default
             */
            input: string;
        };
        /** WorkflowUpdate */
        WorkflowUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            graph?: components["schemas"]["WorkflowGraph"] | null;
            schedule?: components["schemas"]["WorkflowSchedule"] | null;
            /** Delete Protected */
            delete_protected?: boolean | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    signup_api_v1_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    request_password_reset_api_v1_auth_password_reset_request_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_password_reset_api_v1_auth_password_reset_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirm"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_threads_api_v1_threads_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadRead"][];
                };
            };
        };
    };
    create_thread_api_v1_threads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThreadCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_thread_api_v1_threads__thread_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_thread_api_v1_threads__thread_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_thread_api_v1_threads__thread_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThreadUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_messages_api_v1_threads__thread_id__messages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UIMessage"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_api_v1_threads__thread_id__chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description AI SDK UI message stream (SSE) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_agents_api_v1_agents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRead"][];
                };
            };
        };
    };
    create_agent_api_v1_agents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_api_v1_agents__agent_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_agent_api_v1_agents__agent_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_agent_api_v1_agents__agent_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_workflows_api_v1_workflows_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowRead"][];
                };
            };
        };
    };
    create_workflow_api_v1_workflows_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workflow_api_v1_workflows__workflow_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_workflow_api_v1_workflows__workflow_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_workflow_api_v1_workflows__workflow_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_workflow_api_v1_workflows__workflow_id__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowRunRequest"];
            };
        };
        responses: {
            /** @description 노드별 실행 이벤트 (SSE, data: JSON) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description 그래프 검증 실패. detail 에 오류 목록 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_workflow_api_v1_workflows__workflow_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowRead"];
                };
            };
            /** @description 그래프 검증 실패. detail 에 오류 목록 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unpublish_workflow_api_v1_workflows__workflow_id__publish_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_embed_api_v1_workflows__workflow_id__embed_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmbedRead"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_embed_api_v1_workflows__workflow_id__embed_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmbedUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmbedRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_embed_api_v1_workflows__workflow_id__embed_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_workflow_runs_api_v1_workflows__workflow_id__runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_providers_api_v1_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderRead"][];
                };
            };
        };
    };
    create_provider_api_v1_providers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_provider_api_v1_providers__provider_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_provider_api_v1_providers__provider_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_provider_api_v1_providers__provider_id__verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_provider_model_api_v1_providers__provider_id__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelTestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelTestResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_feedback_api_v1_runs__run_id__feedback_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_usage_api_v1_usage_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_credits_api_v1_credits_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreditsRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    user_credits_api_v1_admin_credits_get: {
        parameters: {
            query: {
                email: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreditsRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    grant_credits_api_v1_admin_credits_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreditGrant"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreditsRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_api_keys_api_v1_api_keys_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyRead"][];
                };
            };
        };
    };
    create_api_key_api_v1_api_keys_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiKeyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_api_key_api_v1_api_keys__key_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_workflow_api_v1_ext_workflows__workflow_id__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtRunRequest"];
            };
        };
        responses: {
            /** @description stream=false: 결과 JSON / stream=true: 노드별 실행 이벤트 (SSE) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtRunResult"];
                    "text/event-stream": unknown;
                };
            };
            /** @description 워크플로우 검증 실패. detail 에 오류 목록 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description API 키가 없거나 잘못됨 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 서버 키 모델의 크레딧 부족 */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 워크플로우가 없거나 이 키로 부를 수 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 배포되지 않은 워크플로우 (배포본만 실행한다) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description 요청이 너무 많음 (키 하나당 1분 제한) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_embed_api_v1_public_embeds__token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmbedPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_embed_api_v1_public_embeds__token__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmbedRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmbedRunResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_telegram_api_v1_integrations_telegram_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramStatus"];
                };
            };
        };
    };
    connect_telegram_api_v1_integrations_telegram_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelegramConnect"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disconnect_telegram_api_v1_integrations_telegram_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    test_telegram_api_v1_integrations_telegram_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_tools_api_v1_tools_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolRead"][];
                };
            };
        };
    };
    list_models_api_v1_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsRead"];
                };
            };
        };
    };
    set_default_model_api_v1_models_default_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DefaultModelUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
